# Generated by Django 6.0.6 on 2026-07-17 06:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Official title of the job opening', max_length=255)),
                ('description', models.TextField(help_text='Detailed description of responsibilities and requirements')),
                ('category', models.CharField(choices=[('development', 'Development'), ('design', 'Design & UX'), ('marketing', 'Marketing'), ('management', 'Management')], default='development', help_text='Primary industry/sector classification', max_length=50)),
                ('location', models.CharField(help_text="Physical location (e.g., 'San Francisco, CA' or 'Remote')", max_length=255)),
                ('salary', models.CharField(blank=True, help_text="Optional salary display range (e.g. '$120k - $150k')", max_length=100)),
                ('job_type', models.CharField(choices=[('full_time', 'Full-Time'), ('part_time', 'Part-Time'), ('contract', 'Contract'), ('internship', 'Internship'), ('remote', 'Remote')], default='full_time', help_text='Work arrangement standard', max_length=50)),
                ('experience_level', models.CharField(choices=[('entry', 'Entry Level'), ('mid', 'Mid Level'), ('senior', 'Senior Level'), ('lead', 'Lead / Executive')], default='mid', help_text='Target professional seniority level', max_length=50)),
                ('posted_date', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the job listing was created')),
                ('deadline', models.DateField(blank=True, help_text='Optional application closing date', null=True)),
                ('company', models.ForeignKey(help_text='Company listing this employment opportunity', on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='companies.company')),
            ],
            options={
                'ordering': ['-posted_date'],
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(help_text='Upload applicant resume file (PDF or Doc)', upload_to='resumes/')),
                ('cover_letter', models.TextField(blank=True, help_text='Optional message to the hiring manager')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewing', 'Under Review'), ('interview', 'Interviewing'), ('offered', 'Offered'), ('rejected', 'Rejected')], default='pending', help_text='Current selection stage status', max_length=50)),
                ('applied_date', models.DateTimeField(auto_now_add=True, help_text='Timestamp when application was submitted')),
                ('applicant', models.ForeignKey(help_text='The candidate submitting this application', on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(help_text='The position being applied to', on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.job')),
            ],
            options={
                'ordering': ['-applied_date'],
                'unique_together': {('job', 'applicant')},
            },
        ),
    ]
