# Generated by Django 6.0.6 on 2026-07-17 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full Name of the sender', max_length=255)),
                ('email', models.EmailField(help_text='Email address of the sender', max_length=254)),
                ('subject', models.CharField(help_text='Subject line of the inquiry', max_length=255)),
                ('message', models.TextField(help_text='Inquiry content and message body')),
                ('submitted_date', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the message was submitted')),
                ('is_read', models.BooleanField(default=False, help_text='Tracks whether this message has been read by administrators')),
            ],
            options={
                'ordering': ['-submitted_date'],
            },
        ),
    ]
