# Generated by Django 6.0.6 on 2026-07-17 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='location',
            field=models.CharField(blank=True, help_text='Current city or location', max_length=255),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Contact phone number', max_length=20),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Upload a professional headshot', null=True, upload_to='profile_pics/'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='resume',
            field=models.FileField(blank=True, help_text='Upload your resume document', null=True, upload_to='resumes/'),
        ),
        migrations.AddField(
            model_name='recruiterprofile',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Contact phone number', max_length=20),
        ),
        migrations.AddField(
            model_name='recruiterprofile',
            name='position',
            field=models.CharField(blank=True, help_text='Current professional role/position', max_length=100),
        ),
        migrations.AddField(
            model_name='recruiterprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Upload a professional headshot', null=True, upload_to='profile_pics/'),
        ),
    ]
