# Generated by Django 6.0.6 on 2026-07-17 06:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Unique name of the organization', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Detailed company profile and description')),
                ('website', models.URLField(blank=True, help_text='Link to the official company homepage')),
                ('location', models.CharField(blank=True, help_text='Headquarters physical address/location', max_length=255)),
                ('logo', models.FileField(blank=True, help_text='Upload official company logo image/vector', null=True, upload_to='company_logos/')),
                ('owner', models.ForeignKey(help_text='Recruiter who manages this company profile', on_delete=django.db.models.deletion.CASCADE, related_name='owned_companies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'ordering': ['name'],
            },
        ),
    ]
